### ISSUE TITLE
Support for multiple person

### ISSUE THREAD

**Issue by frankrehfeld** [TJPoorman/home_maintenance#29]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/TJPoorman/home_maintenance/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).
- [x] I have read the "Important Note" section of the readme and this feature request fits the scope of the integration.

### Is your feature request related to a problem? Please describe.

I'm living in a home with my wife and child and we've got a home maintenance plan on paper with tasks per person. I tried to bring this paper based plan into this integration but unfortunately there is no field to define who is responsible for a task.

### Describe the solution you'd like

It would be nice, if would be possible to define an attribute for a task, which holds who is responsible. This attribute could be optional.

### Describe alternatives you've considered

I've thought about using the name of the person, who is responsible, in parenthesis and add it to the title, but it would be a total hustle to use this information from the title in scripts or automations.

### Additional context

This attribute could be used to present the tasks to the responsible person via notifications or on personal dashboards.

**Comment by TJPoorman** [comment]
@frankrehfeld Could you use Labels that are part of Home Assistant for what you're aiming for here?

**Comment by felixschndr** [comment]
I'd love this feature as well.

For the time being I implemented a workaround by using labels. Each task has one label attached to it. The label is the name of the person, which then gets a notification on their respective phone. Maybe it help someone :)
```yaml
alias: Benachrichtigen über Aufgaben
description: ""
triggers:
  - trigger: time
    at: "08:00:00"
conditions: []
actions:
  - variables:
      aufgaben: >-
        {{ integration_entities('home_maintenance') | select('is_state', 'on') |
        list }}
  - alias: Sende für jede Aufgabe eine Benachrichtigung
    repeat:
      sequence:
        - variables:
            user: |-
              {% set labels = ["name_a", "name_b"] %} // Update accordingly
              {% for label in labels%}
                {% if repeat.item in label_entities(label) %}
                  {{ label }}
                  {% break %}
                {% endif %}
              {% endfor %}
        - alias: Sende eine Benachrichtigung
          action: notify.mobile_app_{{user}}_handy
          data:
            data:
              actions:
                - action: Platzhalter
                  title: Morgen erinnern
                - action: RESETTASK_{{repeat.item}}
                  title: Erledigt
            message: >-
              Nächstes Mal in {{ state_attr(repeat.item, 'interval_value') }}
              Tagen
            title: "Aufgabe fällig: {{ state_attr(repeat.item, 'friendly_name') }}"
      for_each: "{{ aufgaben }}"
mode: single
```
